name: Deploy to CloudJiffy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.0'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Prepare SSH keys
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        cat ~/.ssh/id_rsa  # Check the content of the SSH key file (debug)

    - name: Add CloudJiffy host to known hosts
      env:
        CLOUDJIFFY_HOST: ${{ secrets.SSH_HOST }}
      run: |
        ssh-keyscan $CLOUDJIFFY_HOST >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts  # Check the known hosts file (debug)

    - name: Test SSH connection
      env:
        CLOUDJIFFY_USERNAME: ${{ secrets.SSH_USERNAME }}
        CLOUDJIFFY_HOST: ${{ secrets.SSH_HOST }}
      run: |
        ssh -v $CLOUDJIFFY_USERNAME@$CLOUDJIFFY_HOST "echo 'SSH connection successful'"

    - name: Deploy to CloudJiffy
      env:
        CLOUDJIFFY_USERNAME: ${{ secrets.SSH_USERNAME }}
        CLOUDJIFFY_HOST: ${{ secrets.SSH_HOST }}
      run: |
        scp -r ./dist $CLOUDJIFFY_USERNAME@$CLOUDJIFFY_HOST:/home/jelastic/ROOT
        ssh $CLOUDJIFFY_USERNAME@$CLOUDJIFFY_HOST "
          cd /home/jelastic/ROOT &&
          npm install &&
          NODE_OPTIONS='--max-old-space-size=4096' pm2 restart npm --name 'nodejs-parsing-tool' -- run prod
        "
