name: Deploy to CloudJiffy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.0'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to CloudJiffy
      env:
        SSH_KEY_BASE64: ${{ secrets.SSH_KEY_BASE64 }}
        CLOUDJIFFY_USERNAME: ${{ secrets.SSH_USERNAME }}
        CLOUDJIFFY_HOST: ${{ secrets.SSH_HOST }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY_BASE64" | base64 --decode > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p $SSH_PORT $CLOUDJIFFY_HOST >> ~/.ssh/known_hosts
        cat ~/.ssh/id_rsa  # Debugging: Show the private key (ensure it looks correct)
        cat ~/.ssh/known_hosts  # Debugging: Show the contents of the known_hosts file

        # SSH into the server to remove existing project files
        ssh -v -p $SSH_PORT $CLOUDJIFFY_USERNAME@$CLOUDJIFFY_HOST <<EOF
          rm -rf /home/jelastic/ROOT/*
        EOF

        # Use sftp to transfer files
        sftp -P $SSH_PORT $CLOUDJIFFY_USERNAME@$CLOUDJIFFY_HOST <<EOF
        put -r ./dist /home/jelastic/ROOT
        put package.json /home/jelastic/ROOT
        put package-lock.json /home/jelastic/ROOT
        put forever.json /home/jelastic/ROOT
        EOF

        # SSH into the server and perform post-deployment actions
        ssh -v -p $SSH_PORT $CLOUDJIFFY_USERNAME@$CLOUDJIFFY_HOST <<EOF
          cd ROOT &&
          npm install && pm2 restart nodejs-parsing-tool
        EOF
