name: Deploy to CloudJiffy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.0'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to CloudJiffy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        CLOUDJIFFY_USERNAME: ${{ secrets.SSH_USERNAME }}
        CLOUDJIFFY_HOST: ${{ secrets.SSH_HOST }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p $SSH_PORT $CLOUDJIFFY_HOST >> ~/.ssh/known_hosts
        cat ~/.ssh/id_rsa  # Debugging: Show the private key (ensure it looks correct)
        cat ~/.ssh/known_hosts  # Debugging: Show the contents of the known_hosts file
        
        # Use sftp to transfer files
        sftp -P $SSH_PORT $CLOUDJIFFY_USERNAME@$CLOUDJIFFY_HOST <<EOF
        put -r ./dist /home/jelastic/ROOT
        EOF
        
        # SSH into the server and perform post-deployment actions
        ssh -v -p $SSH_PORT $CLOUDJIFFY_USERNAME@$CLOUDJIFFY_HOST "
          cd /home/jelastic/ROOT &&
          npm install &&
          NODE_OPTIONS='--max-old-space-size=4096' pm2 restart npm --name 'nodejs-parsing-tool' -- run prod
        "