name: Deploy to CloudJiffy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p $SSH_PORT $CLOUDJIFFY_HOST >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        CLOUDJIFFY_HOST: ${{ secrets.SSH_HOST }}

    - name: Deploy to CloudJiffy
      run: |
        scp -v -P $SSH_PORT -r ./dist $CLOUDJIFFY_USERNAME@$CLOUDJIFFY_HOST:/home/jelastic/ROOT
        ssh -v -p $SSH_PORT $CLOUDJIFFY_USERNAME@$CLOUDJIFFY_HOST "
          cd /home/jelastic/ROOT &&
          npm install &&
          NODE_OPTIONS='--max-old-space-size=4096' pm2 restart npm --name 'nodejs-parsing-tool' -- run prod
        "
      env:
        SSH_PORT: ${{ secrets.SSH_PORT }}
        CLOUDJIFFY_HOST: ${{ secrets.SSH_HOST }}
        CLOUDJIFFY_USERNAME: ${{ secrets.SSH_USERNAME }}
